name: Build & Upload Site to FTP

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - name: Setup Environment
      run: |
        gem install jekyll bundler
        bundle install
        sudo apt-get install -y lftp
        
    - name: Build Site with Jekyll
      run: JEKYLL_ENV=production bundle exec jekyll build
    
    - name: Upload site to FTP
      env:
        ftp_location: ${{ secrets.FTP_LOCATION }}
        ftp_username: ${{ secrets.FTP_USERNAME }}
        ftp_password: ${{ secrets.FTP_PASSWORD }} 
      run: |
        lftp -v -e "set ftp:ssl-force true; set ssl:verify-certificate no;-e "mirror --exclude proceedings/ --delete --delete-first -R _site/ ./; bye" -u ${ftp_username},${ftp_password} ${ftp_location}
